const ZD_GET_PATHS = [
  { path: "/api/v2/users/me", params: [], summary: "Current user" },
  { path: "/access/login", params: [], summary: "Login" },
  { path: "/api/lotus/assignables/autocomplete.json", params: [], summary: "List assignable groups and agents based on query matched aga" },
  { path: "/api/lotus/assignables/groups.json", params: [], summary: "List assignable groups on the AssigneeField" },
  { path: "/api/lotus/assignables/groups/{group_id}/agents.json", params: ["group_id"], summary: "List assignable agents from a group on the AssigneeField" },
  { path: "/api/v2/{target_type}/{target_id}/relationship_fields/{field_id}/{source_type}", params: ["target_type", "target_id", "field_id", "source_type"], summary: "Get sources by target" },
  { path: "/api/v2/account/features", params: [], summary: "List Account Features" },
  { path: "/api/v2/account/settings", params: [], summary: "Show Settings" },
  { path: "/api/v2/accounts/available", params: [], summary: "Verify Subdomain Availability" },
  { path: "/api/v2/activities", params: [], summary: "List Activities" },
  { path: "/api/v2/activities/{activity_id}", params: ["activity_id"], summary: "Show Activity" },
  { path: "/api/v2/activities/count", params: [], summary: "Count Activities" },
  { path: "/api/v2/approval_workflow_instances/{approval_workflow_instance_id}/approval_requests/{approval_request_id}", params: ["approval_workflow_instance_id", "approval_request_id"], summary: "Show Approval Request" },
  { path: "/api/v2/attachments/{attachment_id}", params: ["attachment_id"], summary: "Show Attachment" },
  { path: "/api/v2/audit_logs", params: [], summary: "List Audit Logs" },
  { path: "/api/v2/audit_logs/{audit_log_id}", params: ["audit_log_id"], summary: "Show Audit Log" },
  { path: "/api/v2/autocomplete/tags", params: [], summary: "Search Tags" },
  { path: "/api/v2/automations", params: [], summary: "List Automations" },
  { path: "/api/v2/automations/{automation_id}", params: ["automation_id"], summary: "Show Automation" },
  { path: "/api/v2/automations/active", params: [], summary: "List Active Automations" },
  { path: "/api/v2/automations/search", params: [], summary: "Search Automations" },
  { path: "/api/v2/bookmarks", params: [], summary: "List Bookmarks" },
  { path: "/api/v2/brand_agents", params: [], summary: "List Brand Agent Memberships" },
  { path: "/api/v2/brand_agents/{brand_agent_id}", params: ["brand_agent_id"], summary: "Show Brand Agent Membership" },
  { path: "/api/v2/brands", params: [], summary: "List Brands" },
  { path: "/api/v2/brands/{brand_id}", params: ["brand_id"], summary: "Show a Brand" },
  { path: "/api/v2/brands/{brand_id}/agents", params: ["brand_id"], summary: "List Agents By Brand" },
  { path: "/api/v2/brands/{brand_id}/check_host_mapping", params: ["brand_id"], summary: "Check Host Mapping Validity for an Existing Brand" },
  { path: "/api/v2/brands/check_host_mapping", params: [], summary: "Check Host Mapping Validity" },
  { path: "/api/v2/channels/twitter/monitored_twitter_handles", params: [], summary: "List Monitored X Handles" },
  { path: "/api/v2/channels/twitter/monitored_twitter_handles/{monitored_twitter_handle_id}", params: ["monitored_twitter_handle_id"], summary: "Show Monitored X Handle" },
  { path: "/api/v2/channels/twitter/tickets/{comment_id}/statuses", params: ["comment_id"], summary: "List Ticket statuses" },
  { path: "/api/v2/custom_objects", params: [], summary: "List Custom Objects" },
  { path: "/api/v2/custom_objects/{custom_object_key}", params: ["custom_object_key"], summary: "Show Custom Object" },
  { path: "/api/v2/custom_objects/{custom_object_key}/access_rules", params: ["custom_object_key"], summary: "List Access Rules" },
  { path: "/api/v2/custom_objects/{custom_object_key}/access_rules/{id}", params: ["custom_object_key", "id"], summary: "Show Access Rule" },
  { path: "/api/v2/custom_objects/{custom_object_key}/access_rules/definitions", params: ["custom_object_key"], summary: "List Access Rule Definitions" },
  { path: "/api/v2/custom_objects/{custom_object_key}/fields", params: ["custom_object_key"], summary: "List Custom Object Fields" },
  { path: "/api/v2/custom_objects/{custom_object_key}/fields/{custom_object_field_key_or_id}", params: ["custom_object_key", "custom_object_field_key_or_id"], summary: "Show Custom Object Field" },
  { path: "/api/v2/custom_objects/{custom_object_key}/limits/field_limit", params: ["custom_object_key"], summary: "Custom Object Fields Limit" },
  { path: "/api/v2/custom_objects/{custom_object_key}/permission_policies", params: ["custom_object_key"], summary: "List Permission Policies" },
  { path: "/api/v2/custom_objects/{custom_object_key}/permission_policies/{id}", params: ["custom_object_key", "id"], summary: "Show Permission Policy" },
  { path: "/api/v2/custom_objects/{custom_object_key}/records", params: ["custom_object_key"], summary: "List Custom Object Records" },
  { path: "/api/v2/custom_objects/{custom_object_key}/records/{custom_object_record_id}", params: ["custom_object_key", "custom_object_record_id"], summary: "Show Custom Object Record" },
  { path: "/api/v2/custom_objects/{custom_object_key}/records/{record_id}/attachments", params: ["custom_object_key", "record_id"], summary: "List Custom Object Record Attachments" },
  { path: "/api/v2/custom_objects/{custom_object_key}/records/{record_id}/attachments/{id}/download", params: ["custom_object_key", "record_id", "id"], summary: "Download Custom Object Record Attachment" },
  { path: "/api/v2/custom_objects/{custom_object_key}/records/autocomplete", params: ["custom_object_key"], summary: "Autocomplete Custom Object Record Search" },
  { path: "/api/v2/custom_objects/{custom_object_key}/records/count", params: ["custom_object_key"], summary: "Count Custom Object Records" },
  { path: "/api/v2/custom_objects/{custom_object_key}/records/search", params: ["custom_object_key"], summary: "Search Custom Object Records" },
  { path: "/api/v2/custom_objects/{custom_object_key}/triggers", params: ["custom_object_key"], summary: "List Object Triggers" },
  { path: "/api/v2/custom_objects/{custom_object_key}/triggers/{trigger_id}", params: ["custom_object_key", "trigger_id"], summary: "Show Object Trigger" },
  { path: "/api/v2/custom_objects/{custom_object_key}/triggers/active", params: ["custom_object_key"], summary: "List Active Object Triggers" },
  { path: "/api/v2/custom_objects/{custom_object_key}/triggers/definitions", params: ["custom_object_key"], summary: "List Object Trigger Action and Condition Definitions" },
  { path: "/api/v2/custom_objects/{custom_object_key}/triggers/search", params: ["custom_object_key"], summary: "Search Object Triggers" },
  { path: "/api/v2/custom_objects/limits/object_limit", params: [], summary: "Custom Objects Limit" },
  { path: "/api/v2/custom_objects/limits/record_limit", params: [], summary: "Custom Object Records Limit" },
  { path: "/api/v2/custom_roles", params: [], summary: "List Custom Roles" },
  { path: "/api/v2/custom_roles/{custom_role_id}", params: ["custom_role_id"], summary: "Show Custom Role" },
  { path: "/api/v2/custom_statuses", params: [], summary: "List Custom Ticket Statuses" },
  { path: "/api/v2/custom_statuses/{custom_status_id}", params: ["custom_status_id"], summary: "Show Custom Ticket Status" },
  { path: "/api/v2/deleted_tickets", params: [], summary: "List Deleted Tickets" },
  { path: "/api/v2/deleted_users", params: [], summary: "List Deleted Users" },
  { path: "/api/v2/deleted_users/{deleted_user_id}", params: ["deleted_user_id"], summary: "Show Deleted User" },
  { path: "/api/v2/deleted_users/count", params: [], summary: "Count Deleted Users" },
  { path: "/api/v2/deletion_schedules", params: [], summary: "List Deletion Schedules" },
  { path: "/api/v2/deletion_schedules/{deletion_schedule_id}", params: ["deletion_schedule_id"], summary: "Get Deletion Schedule" },
  { path: "/api/v2/dynamic_content/items", params: [], summary: "List Items" },
  { path: "/api/v2/dynamic_content/items/{dynamic_content_item_id}", params: ["dynamic_content_item_id"], summary: "Show Item" },
  { path: "/api/v2/dynamic_content/items/{dynamic_content_item_id}/variants", params: ["dynamic_content_item_id"], summary: "List Variants" },
  { path: "/api/v2/dynamic_content/items/{dynamic_content_item_id}/variants/{dynamic_content_variant_id}", params: ["dynamic_content_item_id", "dynamic_content_variant_id"], summary: "Show Variant" },
  { path: "/api/v2/dynamic_content/items/show_many", params: [], summary: "Show Many Items" },
  { path: "/api/v2/email_notifications", params: [], summary: "List Email Notifications" },
  { path: "/api/v2/email_notifications/{notification_id}", params: ["notification_id"], summary: "Show Email Notification" },
  { path: "/api/v2/email_notifications/show_many", params: [], summary: "Show Many Email Notifications" },
  { path: "/api/v2/end_users/{user_id}/identities", params: ["user_id"], summary: "List End User Identities" },
  { path: "/api/v2/end_users/{user_id}/identities/{user_identity_id}", params: ["user_id", "user_identity_id"], summary: "Show End User Identity" },
  { path: "/api/v2/group_memberships", params: [], summary: "List Memberships" },
  { path: "/api/v2/group_memberships/{group_membership_id}", params: ["group_membership_id"], summary: "Show Membership" },
  { path: "/api/v2/group_memberships/assignable", params: [], summary: "List Assignable Memberships" },
  { path: "/api/v2/group_slas/policies", params: [], summary: "List Group SLA Policies" },
  { path: "/api/v2/group_slas/policies/{group_sla_policy_id}", params: ["group_sla_policy_id"], summary: "Show Group SLA Policy" },
  { path: "/api/v2/group_slas/policies/definitions", params: [], summary: "Retrieve Supported Filter Definition Items" },
  { path: "/api/v2/groups", params: [], summary: "List Groups" },
  { path: "/api/v2/groups/{group_id}", params: ["group_id"], summary: "Show Group" },
  { path: "/api/v2/groups/{group_id}/memberships", params: ["group_id"], summary: "List Memberships By Group" },
  { path: "/api/v2/groups/{group_id}/memberships/assignable", params: ["group_id"], summary: "List Assignable Memberships By Group" },
  { path: "/api/v2/groups/{group_id}/users", params: ["group_id"], summary: "List Users By Group" },
  { path: "/api/v2/groups/{group_id}/users/count", params: ["group_id"], summary: "Count Users By Group" },
  { path: "/api/v2/groups/assignable", params: [], summary: "List Assignable Groups" },
  { path: "/api/v2/groups/count", params: [], summary: "Count Groups" },
  { path: "/api/v2/incremental/{incremental_resource}/sample", params: ["incremental_resource"], summary: "Incremental Sample Export" },
  { path: "/api/v2/incremental/custom_objects/{custom_object_key}/cursor", params: ["custom_object_key"], summary: "Incremental Custom Object Record Export, Cursor Based" },
  { path: "/api/v2/incremental/organizations", params: [], summary: "Incremental Organization Export" },
  { path: "/api/v2/incremental/routing/attribute_values", params: [], summary: "Incremental Attributes Values Export" },
  { path: "/api/v2/incremental/routing/attributes", params: [], summary: "Incremental Attributes Export" },
  { path: "/api/v2/incremental/routing/instance_values", params: [], summary: "Incremental Instance Values Export" },
  { path: "/api/v2/incremental/ticket_events", params: [], summary: "Incremental Ticket Event Export" },
  { path: "/api/v2/incremental/ticket_metric_events", params: [], summary: "List Ticket Metric Events" },
  { path: "/api/v2/incremental/tickets", params: [], summary: "Incremental Ticket Export, Time Based" },
  { path: "/api/v2/incremental/tickets/cursor", params: [], summary: "Incremental Ticket Export, Cursor Based" },
  { path: "/api/v2/incremental/users", params: [], summary: "Incremental User Export, Time Based" },
  { path: "/api/v2/incremental/users/cursor", params: [], summary: "Incremental User Export, Cursor Based" },
  { path: "/api/v2/it_asset_management/asset_types", params: [], summary: "List Asset Types" },
  { path: "/api/v2/it_asset_management/asset_types/{asset_type_id}", params: ["asset_type_id"], summary: "Show Asset Type" },
  { path: "/api/v2/it_asset_management/asset_types/{asset_type_id}/fields", params: ["asset_type_id"], summary: "List Asset Fields" },
  { path: "/api/v2/it_asset_management/asset_types/{asset_type_id}/fields/{asset_type_field_id}", params: ["asset_type_id", "asset_type_field_id"], summary: "Show Asset Field" },
  { path: "/api/v2/it_asset_management/assets", params: [], summary: "List Assets" },
  { path: "/api/v2/it_asset_management/assets/{asset_id}", params: ["asset_id"], summary: "Show Asset" },
  { path: "/api/v2/it_asset_management/locations", params: [], summary: "List Asset Locations" },
  { path: "/api/v2/it_asset_management/locations/{location_id}", params: ["location_id"], summary: "Show Asset Location" },
  { path: "/api/v2/it_asset_management/statuses", params: [], summary: "List Asset Statuses" },
  { path: "/api/v2/it_asset_management/statuses/{status_id}", params: ["status_id"], summary: "Show Asset Status" },
  { path: "/api/v2/job_statuses", params: [], summary: "List Job Statuses" },
  { path: "/api/v2/job_statuses/{job_status_id}", params: ["job_status_id"], summary: "Show Job Status" },
  { path: "/api/v2/job_statuses/show_many", params: [], summary: "Show Many Job Statuses" },
  { path: "/api/v2/locales", params: [], summary: "List Locales" },
  { path: "/api/v2/locales/{locale_id}", params: ["locale_id"], summary: "Show Locale" },
  { path: "/api/v2/locales/agent", params: [], summary: "List Locales for Agent" },
  { path: "/api/v2/locales/current", params: [], summary: "Show Current Locale" },
  { path: "/api/v2/locales/detect_best_locale", params: [], summary: "Detect Best Language for User" },
  { path: "/api/v2/locales/public", params: [], summary: "List Available Public Locales" },
  { path: "/api/v2/macros", params: [], summary: "List Macros" },
  { path: "/api/v2/macros/{macro_id}", params: ["macro_id"], summary: "Show Macro" },
  { path: "/api/v2/macros/{macro_id}/apply", params: ["macro_id"], summary: "Show Changes to Ticket" },
  { path: "/api/v2/macros/{macro_id}/attachments", params: ["macro_id"], summary: "List Macro Attachments" },
  { path: "/api/v2/macros/actions", params: [], summary: "List Supported Actions for Macros" },
  { path: "/api/v2/macros/active", params: [], summary: "List Active Macros" },
  { path: "/api/v2/macros/attachments/{attachment_id}", params: ["attachment_id"], summary: "Show Macro Attachment" },
  { path: "/api/v2/macros/categories", params: [], summary: "List Macro Categories" },
  { path: "/api/v2/macros/definitions", params: [], summary: "List Macro Action Definitions" },
  { path: "/api/v2/macros/new", params: [], summary: "Show Macro Replica" },
  { path: "/api/v2/macros/search", params: [], summary: "Search Macros" },
  { path: "/api/v2/oauth/clients", params: [], summary: "List Clients" },
  { path: "/api/v2/oauth/clients/{oauth_client_id}", params: ["oauth_client_id"], summary: "Show Client" },
  { path: "/api/v2/oauth/global_clients", params: [], summary: "List Global OAuth Clients" },
  { path: "/api/v2/oauth/global_clients/{global_client_id}", params: ["global_client_id"], summary: "Show Global OAuth Client" },
  { path: "/api/v2/oauth/global_clients/token_summary", params: [], summary: "Show Token summary for Global OAuth Clients" },
  { path: "/api/v2/oauth/tokens", params: [], summary: "List Tokens" },
  { path: "/api/v2/oauth/tokens/{oauth_token_id}", params: ["oauth_token_id"], summary: "Show Token" },
  { path: "/api/v2/oauth/tokens/current", params: [], summary: "Show Current Token" },
  { path: "/api/v2/object_layouts/{object_type}/essentials_card", params: ["object_type"], summary: "Show Essentials Card" },
  { path: "/api/v2/object_layouts/essentials_cards", params: [], summary: "List of Essentials Cards" },
  { path: "/api/v2/organization_fields", params: [], summary: "List Organization Fields" },
  { path: "/api/v2/organization_fields/{organization_field_id}", params: ["organization_field_id"], summary: "Show Organization Field" },
  { path: "/api/v2/organization_memberships", params: [], summary: "List Memberships" },
  { path: "/api/v2/organization_memberships/{organization_membership_id}", params: ["organization_membership_id"], summary: "Show Membership" },
  { path: "/api/v2/organization_merges/{organization_merge_id}", params: ["organization_merge_id"], summary: "Show Organization Merge" },
  { path: "/api/v2/organization_subscriptions", params: [], summary: "List Organization Subscriptions" },
  { path: "/api/v2/organization_subscriptions/{organization_subscription_id}", params: ["organization_subscription_id"], summary: "Show Organization Subscription" },
  { path: "/api/v2/organizations", params: [], summary: "List Organizations" },
  { path: "/api/v2/organizations/{organization_id}", params: ["organization_id"], summary: "Show Organization" },
  { path: "/api/v2/organizations/{organization_id}/merges", params: ["organization_id"], summary: "List Organization Merges" },
  { path: "/api/v2/organizations/{organization_id}/organization_memberships", params: ["organization_id"], summary: "List Organization Memberships by Organization" },
  { path: "/api/v2/organizations/{organization_id}/related", params: ["organization_id"], summary: "Show Organization's Related Information" },
  { path: "/api/v2/organizations/{organization_id}/requests", params: ["organization_id"], summary: "List Organization Requests" },
  { path: "/api/v2/organizations/{organization_id}/subscriptions", params: ["organization_id"], summary: "List Subscriptions By Organization" },
  { path: "/api/v2/organizations/{organization_id}/tags", params: ["organization_id"], summary: "List Organization Tags" },
  { path: "/api/v2/organizations/{organization_id}/tickets", params: ["organization_id"], summary: "List Organization Tickets" },
  { path: "/api/v2/organizations/{organization_id}/tickets/count", params: ["organization_id"], summary: "Count Organization Tickets" },
  { path: "/api/v2/organizations/{organization_id}/users", params: ["organization_id"], summary: "List Organization Users" },
  { path: "/api/v2/organizations/{organization_id}/users/count", params: ["organization_id"], summary: "Count Organization Users" },
  { path: "/api/v2/organizations/autocomplete", params: [], summary: "Autocomplete Organizations" },
  { path: "/api/v2/organizations/count", params: [], summary: "Count Organizations" },
  { path: "/api/v2/organizations/search", params: [], summary: "Search Organizations" },
  { path: "/api/v2/organizations/show_many", params: [], summary: "Show Many Organizations" },
  { path: "/api/v2/problems", params: [], summary: "List Ticket Problems" },
  { path: "/api/v2/queues", params: [], summary: "List queues" },
  { path: "/api/v2/queues/{queue_id}", params: ["queue_id"], summary: "Show Queue" },
  { path: "/api/v2/queues/definitions", params: [], summary: "List Queue Definitions" },
  { path: "/api/v2/recipient_addresses", params: [], summary: "List Support Addresses" },
  { path: "/api/v2/recipient_addresses/{support_address_id}", params: ["support_address_id"], summary: "Show Support Address" },
  { path: "/api/v2/relationships/definitions/{target_type}", params: ["target_type"], summary: "Filter Definitions" },
  { path: "/api/v2/remote_authentications", params: [], summary: "List Remote Authentications" },
  { path: "/api/v2/requests", params: [], summary: "List Requests" },
  { path: "/api/v2/requests/{request_id}", params: ["request_id"], summary: "Show Request" },
  { path: "/api/v2/requests/{request_id}/comments", params: ["request_id"], summary: "Listing Comments" },
  { path: "/api/v2/requests/{request_id}/comments/{ticket_comment_id}", params: ["request_id", "ticket_comment_id"], summary: "Getting Comments" },
  { path: "/api/v2/requests/ccd", params: [], summary: "List CCD Requests" },
  { path: "/api/v2/requests/open", params: [], summary: "List Open Requests" },
  { path: "/api/v2/requests/search", params: [], summary: "Search Requests" },
  { path: "/api/v2/requests/solved", params: [], summary: "List Solved Requests" },
  { path: "/api/v2/resource_collections", params: [], summary: "List Resource Collections" },
  { path: "/api/v2/resource_collections/{resource_collection_id}", params: ["resource_collection_id"], summary: "Show Resource Collection" },
  { path: "/api/v2/routing/agents/{user_id}/instance_values", params: ["user_id"], summary: "List Agent Attribute Values" },
  { path: "/api/v2/routing/agents/instance_values", params: [], summary: "List Attribute Values for Many Agents" },
  { path: "/api/v2/routing/attributes", params: [], summary: "List Account Attributes" },
  { path: "/api/v2/routing/attributes/{attribute_id}", params: ["attribute_id"], summary: "Show Attribute" },
  { path: "/api/v2/routing/attributes/{attribute_id}/values", params: ["attribute_id"], summary: "List Attribute Values for an Attribute" },
  { path: "/api/v2/routing/attributes/{attribute_id}/values/{attribute_value_id}", params: ["attribute_id", "attribute_value_id"], summary: "Show Attribute Value" },
  { path: "/api/v2/routing/attributes/definitions", params: [], summary: "List Routing Attribute Definitions" },
  { path: "/api/v2/routing/requirements/fulfilled", params: [], summary: "List Tickets Fulfilled by a User" },
  { path: "/api/v2/routing/tickets/{ticket_id}/instance_values", params: ["ticket_id"], summary: "List Ticket Attribute Values" },
  { path: "/api/v2/satisfaction_ratings", params: [], summary: "List Satisfaction Ratings" },
  { path: "/api/v2/satisfaction_ratings/{satisfaction_rating_id}", params: ["satisfaction_rating_id"], summary: "Show Satisfaction Rating" },
  { path: "/api/v2/satisfaction_ratings/count", params: [], summary: "Count Satisfaction Ratings" },
  { path: "/api/v2/satisfaction_reasons", params: [], summary: "List Reasons for Satisfaction Rating" },
  { path: "/api/v2/satisfaction_reasons/{satisfaction_reason_id}", params: ["satisfaction_reason_id"], summary: "Show Reason for Satisfaction Rating" },
  { path: "/api/v2/search", params: [], summary: "List Search Results" },
  { path: "/api/v2/search/count", params: [], summary: "Show Results Count" },
  { path: "/api/v2/search/export", params: [], summary: "Export Search Results" },
  { path: "/api/v2/security_settings", params: [], summary: "Show Security Settings" },
  { path: "/api/v2/sessions", params: [], summary: "List Sessions" },
  { path: "/api/v2/sharing_agreements", params: [], summary: "List Sharing Agreements" },
  { path: "/api/v2/sharing_agreements/{sharing_agreement_id}", params: ["sharing_agreement_id"], summary: "Show a Sharing Agreement" },
  { path: "/api/v2/skips", params: [], summary: "List All Skips" },
  { path: "/api/v2/slas/policies", params: [], summary: "List SLA Policies" },
  { path: "/api/v2/slas/policies/{sla_policy_id}", params: ["sla_policy_id"], summary: "Show SLA Policy" },
  { path: "/api/v2/slas/policies/definitions", params: [], summary: "Retrieve Supported Filter Definition Items" },
  { path: "/api/v2/suspended_tickets", params: [], summary: "List Suspended Tickets" },
  { path: "/api/v2/suspended_tickets/{id}", params: ["id"], summary: "Show Suspended Ticket" },
  { path: "/api/v2/tags", params: [], summary: "List Tags" },
  { path: "/api/v2/tags/count", params: [], summary: "Count Tags" },
  { path: "/api/v2/target_failures", params: [], summary: "List Target Failures" },
  { path: "/api/v2/target_failures/{target_failure_id}", params: ["target_failure_id"], summary: "Show Target Failure" },
  { path: "/api/v2/targets", params: [], summary: "List Targets" },
  { path: "/api/v2/targets/{target_id}", params: ["target_id"], summary: "Show Target" },
  { path: "/api/v2/ticket_audits", params: [], summary: "List All Ticket Audits" },
  { path: "/api/v2/ticket_content_pins", params: [], summary: "List Ticket Content Pins" },
  { path: "/api/v2/ticket_fields", params: [], summary: "List Ticket Fields" },
  { path: "/api/v2/ticket_fields/{ticket_field_id}", params: ["ticket_field_id"], summary: "Show Ticket Field" },
  { path: "/api/v2/ticket_fields/{ticket_field_id}/options", params: ["ticket_field_id"], summary: "List Ticket Field Options" },
  { path: "/api/v2/ticket_fields/{ticket_field_id}/options/{ticket_field_option_id}", params: ["ticket_field_id", "ticket_field_option_id"], summary: "Show Ticket Field Option" },
  { path: "/api/v2/ticket_fields/count", params: [], summary: "Count Ticket Fields" },
  { path: "/api/v2/ticket_form_statuses", params: [], summary: "List Ticket Form Statuses" },
  { path: "/api/v2/ticket_form_statuses/show_many", params: [], summary: "Show Many Ticket Form Statuses" },
  { path: "/api/v2/ticket_forms", params: [], summary: "List Ticket Forms" },
  { path: "/api/v2/ticket_forms/{ticket_form_id}", params: ["ticket_form_id"], summary: "Show Ticket Form" },
  { path: "/api/v2/ticket_forms/{ticket_form_id}/ticket_form_statuses", params: ["ticket_form_id"], summary: "List Ticket Form Statuses of a Ticket Form" },
  { path: "/api/v2/ticket_forms/show_many", params: [], summary: "Show Many Ticket Forms" },
  { path: "/api/v2/ticket_metrics", params: [], summary: "List Ticket Metrics" },
  { path: "/api/v2/ticket_metrics/{ticket_metric_id}", params: ["ticket_metric_id"], summary: "Show Ticket Metrics" },
  { path: "/api/v2/tickets", params: [], summary: "List Tickets" },
  { path: "/api/v2/tickets/{ticket_id}", params: ["ticket_id"], summary: "Show Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/audits", params: ["ticket_id"], summary: "List Audits for a Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/audits/{ticket_audit_id}", params: ["ticket_id", "ticket_audit_id"], summary: "Show Audit" },
  { path: "/api/v2/tickets/{ticket_id}/audits/count", params: ["ticket_id"], summary: "Count Audits for a Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/collaborators", params: ["ticket_id"], summary: "List Collaborators for a Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/comments", params: ["ticket_id"], summary: "List Comments" },
  { path: "/api/v2/tickets/{ticket_id}/comments/count", params: ["ticket_id"], summary: "Count Ticket Comments" },
  { path: "/api/v2/tickets/{ticket_id}/conversation_log", params: ["ticket_id"], summary: "List Conversation log for Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/email_ccs", params: ["ticket_id"], summary: "List Email CCs for a Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/followers", params: ["ticket_id"], summary: "List Followers for a Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/incidents", params: ["ticket_id"], summary: "List Ticket Incidents" },
  { path: "/api/v2/tickets/{ticket_id}/macros/{macro_id}/apply", params: ["ticket_id", "macro_id"], summary: "Show Ticket After Changes" },
  { path: "/api/v2/tickets/{ticket_id}/metrics", params: ["ticket_id"], summary: "Show Ticket Metrics By Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/related", params: ["ticket_id"], summary: "Ticket Related Information" },
  { path: "/api/v2/tickets/{ticket_id}/skips", params: ["ticket_id"], summary: "List Ticket Skips By Ticket" },
  { path: "/api/v2/tickets/{ticket_id}/tags", params: ["ticket_id"], summary: "List Resource Tags" },
  { path: "/api/v2/tickets/count", params: [], summary: "Count Tickets" },
  { path: "/api/v2/tickets/recent", params: [], summary: "List Recent Tickets" },
  { path: "/api/v2/tickets/show_many", params: [], summary: "Show Multiple Tickets" },
  { path: "/api/v2/trigger_categories", params: [], summary: "List Ticket Trigger Categories" },
  { path: "/api/v2/trigger_categories/{trigger_category_id}", params: ["trigger_category_id"], summary: "Show Ticket Trigger Category" },
  { path: "/api/v2/triggers", params: [], summary: "List Ticket Triggers" },
  { path: "/api/v2/triggers/{trigger_id}", params: ["trigger_id"], summary: "Show Ticket Trigger" },
  { path: "/api/v2/triggers/{trigger_id}/revisions", params: ["trigger_id"], summary: "List Ticket Trigger Revisions" },
  { path: "/api/v2/triggers/{trigger_id}/revisions/{trigger_revision_id}", params: ["trigger_id", "trigger_revision_id"], summary: "Show Ticket Trigger Revision" },
  { path: "/api/v2/triggers/active", params: [], summary: "List Active Ticket Triggers" },
  { path: "/api/v2/triggers/definitions", params: [], summary: "List Ticket Trigger Action and Condition Definitions" },
  { path: "/api/v2/triggers/search", params: [], summary: "Search Ticket Triggers" },
  { path: "/api/v2/user_fields", params: [], summary: "List User Fields" },
  { path: "/api/v2/user_fields/{user_field_id}", params: ["user_field_id"], summary: "Show User Field" },
  { path: "/api/v2/user_fields/{user_field_id}/options", params: ["user_field_id"], summary: "List User Field Options" },
  { path: "/api/v2/user_fields/{user_field_id}/options/{user_field_option_id}", params: ["user_field_id", "user_field_option_id"], summary: "Show a User Field Option" },
  { path: "/api/v2/users", params: [], summary: "List Users" },
  { path: "/api/v2/users/{user_id}", params: ["user_id"], summary: "Show User" },
  { path: "/api/v2/users/{user_id}/brand_agents", params: ["user_id"], summary: "List Brand Agent Memberships By User" },
  { path: "/api/v2/users/{user_id}/brand_agents/{brand_agent_id}", params: ["user_id", "brand_agent_id"], summary: "Show Brand Agent Membership By User" },
  { path: "/api/v2/users/{user_id}/compliance_deletion_statuses", params: ["user_id"], summary: "Show Compliance Deletion Statuses" },
  { path: "/api/v2/users/{user_id}/entitlements/full", params: ["user_id"], summary: "Get Full User Entitlements" },
  { path: "/api/v2/users/{user_id}/group_memberships", params: ["user_id"], summary: "List Group Memberships by User" },
  { path: "/api/v2/users/{user_id}/group_memberships/{group_membership_id}", params: ["user_id", "group_membership_id"], summary: "Show User's Group Membership" },
  { path: "/api/v2/users/{user_id}/groups", params: ["user_id"], summary: "List User Groups" },
  { path: "/api/v2/users/{user_id}/groups/count", params: ["user_id"], summary: "Count User Groups" },
  { path: "/api/v2/users/{user_id}/identities", params: ["user_id"], summary: "List Identities" },
  { path: "/api/v2/users/{user_id}/identities/{user_identity_id}", params: ["user_id", "user_identity_id"], summary: "Show Identity" },
  { path: "/api/v2/users/{user_id}/organization_memberships", params: ["user_id"], summary: "List Organization Memberships by User" },
  { path: "/api/v2/users/{user_id}/organization_memberships/{organization_membership_id}", params: ["user_id", "organization_membership_id"], summary: "Show Organization Membership by User" },
  { path: "/api/v2/users/{user_id}/organization_subscriptions", params: ["user_id"], summary: "List User's Organization Subscriptions" },
  { path: "/api/v2/users/{user_id}/organizations", params: ["user_id"], summary: "List User Organizations" },
  { path: "/api/v2/users/{user_id}/organizations/count", params: ["user_id"], summary: "Count User's Organizations" },
  { path: "/api/v2/users/{user_id}/password/requirements", params: ["user_id"], summary: "List password requirements" },
  { path: "/api/v2/users/{user_id}/related", params: ["user_id"], summary: "Show User Related Information" },
  { path: "/api/v2/users/{user_id}/requests", params: ["user_id"], summary: "List User Requests" },
  { path: "/api/v2/users/{user_id}/sessions", params: ["user_id"], summary: "List Sessions for User" },
  { path: "/api/v2/users/{user_id}/sessions/{session_id}", params: ["user_id", "session_id"], summary: "Show Session" },
  { path: "/api/v2/users/{user_id}/skips", params: ["user_id"], summary: "List Ticket Skips" },
  { path: "/api/v2/users/{user_id}/tags", params: ["user_id"], summary: "List User Tags" },
  { path: "/api/v2/users/{user_id}/tickets/assigned", params: ["user_id"], summary: "List User Assigned Tickets" },
  { path: "/api/v2/users/{user_id}/tickets/assigned/count", params: ["user_id"], summary: "Count User Assigned Tickets" },
  { path: "/api/v2/users/{user_id}/tickets/ccd", params: ["user_id"], summary: "List User CCD Tickets" },
  { path: "/api/v2/users/{user_id}/tickets/ccd/count", params: ["user_id"], summary: "Count User CCD Tickets" },
  { path: "/api/v2/users/{user_id}/tickets/followed", params: ["user_id"], summary: "List User Followed Tickets" },
  { path: "/api/v2/users/{user_id}/tickets/requested", params: ["user_id"], summary: "List User Requested Tickets" },
  { path: "/api/v2/users/autocomplete", params: [], summary: "Autocomplete Users" },
  { path: "/api/v2/users/count", params: [], summary: "Count Users" },
  { path: "/api/v2/users/me", params: [], summary: "Show Self" },
  { path: "/api/v2/users/me/oauth/clients", params: [], summary: "List Current User's Clients" },
  { path: "/api/v2/users/me/session", params: [], summary: "Show the Currently Authenticated Session" },
  { path: "/api/v2/users/me/session/renew", params: [], summary: "Renew the current session" },
  { path: "/api/v2/users/search", params: [], summary: "Search Users" },
  { path: "/api/v2/users/show_many", params: [], summary: "Show Many Users" },
  { path: "/api/v2/view_categories", params: [], summary: "List View Categories" },
  { path: "/api/v2/views", params: [], summary: "List Views" },
  { path: "/api/v2/views/{view_id}", params: ["view_id"], summary: "Show View" },
  { path: "/api/v2/views/{view_id}/count", params: ["view_id"], summary: "Count Tickets in View" },
  { path: "/api/v2/views/{view_id}/execute", params: ["view_id"], summary: "Execute View" },
  { path: "/api/v2/views/{view_id}/export", params: ["view_id"], summary: "Export View" },
  { path: "/api/v2/views/{view_id}/tickets", params: ["view_id"], summary: "List Tickets From a View" },
  { path: "/api/v2/views/active", params: [], summary: "List Active Views" },
  { path: "/api/v2/views/compact", params: [], summary: "List Views - Compact" },
  { path: "/api/v2/views/count", params: [], summary: "Count Views" },
  { path: "/api/v2/views/count_many", params: [], summary: "Count Tickets in Views" },
  { path: "/api/v2/views/search", params: [], summary: "Search Views" },
  { path: "/api/v2/views/show_many", params: [], summary: "List Views By ID" },
  { path: "/api/v2/workspaces", params: [], summary: "List Workspaces" },
  { path: "/api/v2/workspaces/{workspace_id}", params: ["workspace_id"], summary: "Show Workspace" },
  { path: "/auth/api/one_time_password", params: [], summary: "Show OTP setting" },
];
