const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const SIDEPANEL_HTML_PATH = path.join(ROOT, "sidepanel.html");
const SIDEPANEL_JS_PATH = path.join(ROOT, "sidepanel.js");
const SIDEPANEL_CSS_PATH = path.join(ROOT, "sidepanel.css");
const CONTENT_PATH = path.join(ROOT, "content.js");
const BACKGROUND_PATH = path.join(ROOT, "background.js");
const SLACK_TOKEN_BRIDGE_PATH = path.join(ROOT, "slack-token-bridge.js");
const OPTIONS_PATH = path.join(ROOT, "options.js");
const OPTIONS_HTML_PATH = path.join(ROOT, "options.html");

test("sidepanel uses SLACKTIVATED indicator + Blondie dual-mode Slack delivery", () => {
  const html = fs.readFileSync(SIDEPANEL_HTML_PATH, "utf8");
  const js = fs.readFileSync(SIDEPANEL_JS_PATH, "utf8");

  assert.match(html, /id="zipSlacktivatedBtn"/);
  assert.match(html, /id="zipContextMenuSlacktivateSection"/);
  assert.match(html, /id="zipContextMenuSlacktivateContent"/);
  assert.match(html, /id="zipContextMenuSlacktivateInput"/);
  assert.match(html, /id="zipContextMenuAskTeam"/);
  assert.doesNotMatch(html, /id="zipContextMenuSlackMe"/);
  assert.match(html, /id="zipSlackMeDialogBackdrop"/);
  assert.match(html, /id="zipSlackMeDialog"/);
  assert.match(html, /id="zipSlackMeRecipientSelect"/);
  assert.match(html, /id="zipSlackMeRecipientHelp"/);
  assert.match(html, /id="zipSlackMeSendLabel"[\s\S]*>SHARE</);
  assert.match(html, /id="zipSlackItToMeBtn"[\s\S]*Click sends to ZipTool panel\. RE-SLACKTIVATE to load pass-transition teammates\./);
  assert.doesNotMatch(html, /@SLACK ME/);
  assert.doesNotMatch(html, /id="zipSlackLoginBtn"/);

  assert.match(js, /SLACKTIVATED_LOGIN_TOOLTIP/);
  assert.match(js, /const ZIP_REQUIRED_SLACK_BOT_TOKEN_FIELD = "slacktivation\.bot_token";/);
  assert.match(js, /SLACK_IT_TO_ME_CACHED_PASS_TRANSITION_TOOLTIP = "Click sends to ZipTool panel\. Shift\+Click uses the cached PASS-TRANSITION roster\."/);
  assert.match(js, /SLACK_IT_TO_ME_REHYDRATE_TOOLTIP = "Click sends to ZipTool panel\. RE-SLACKTIVATE to load pass-transition teammates\."/);
  assert.match(js, /PASS_TRANSITION_CACHE_MISSING_MESSAGE = "No PASS-TRANSITION roster is cached yet\. RE-SLACKTIVATE to load members\."/);
  assert.match(js, /slacktivatedBtn:\s*\$\("zipSlacktivatedBtn"\)/);
  assert.match(js, /contextMenuSlacktivateSection:\s*\$\("zipContextMenuSlacktivateSection"\)/);
  assert.match(js, /contextMenuSlacktivateContent:\s*\$\("zipContextMenuSlacktivateContent"\)/);
  assert.match(js, /contextMenuSlacktivateInput:\s*\$\("zipContextMenuSlacktivateInput"\)/);
  assert.doesNotMatch(js, /contextMenuSlackMe:\s*\$\("zipContextMenuSlackMe"\)/);
  assert.match(js, /slackMeDialogBackdrop:\s*\$\("zipSlackMeDialogBackdrop"\)/);
  assert.match(js, /slackMeRecipientSelect:\s*\$\("zipSlackMeRecipientSelect"\)/);
  assert.match(js, /slackMeSendLabel:\s*\$\("zipSlackMeSendLabel"\)/);
  assert.match(js, /function loadPassTransitionRecipients\(options\)/);
  assert.match(js, /function buildPassTransitionShareMarkdown\(rows,\s*noteText,\s*recipient\)/);
  assert.match(js, /function sendPassTransitionShareFromDialog\(\)/);
  assert.match(js, /function isPassTransitionRecipientCurrentSlackUser\(recipient\)/);
  assert.match(js, /function syncSlackMeRecipientIdentity\(\)/);
  assert.match(js, /function normalizeSlackMeDraftText\(value\)/);
  assert.match(js, /function convertSlackMeDraftToMrkdwn\(value\)/);
  assert.match(js, /function handleSlackMeListContinuationEnter\(\)/);
  assert.match(js, /function applySlackMeToolbarAction\(action\)/);
  assert.match(js, /async function openSlackMeDialog\(options\)/);
  assert.match(js, /async function sendSlackMeNoteFromDialog\(\)\s*\{\s*return sendPassTransitionShareFromDialog\(\);\s*\}/);
  assert.match(js, /openSlackMeDialog\(\{\}\)\.catch/);
  assert.match(js, /openSlackMeDialog\(\{\s*selectedRecipientId\s*\}\);/);
  assert.match(js, /els\.slackMeRecipientSelect\.addEventListener\("change"/);
  assert.match(js, /if \(event\.key !== "Enter"\) return;/);
  assert.match(js, /if \(event\.metaKey \|\| event\.ctrlKey\) \{/);
  assert.match(js, /if \(event\.shiftKey \|\| event\.altKey\) return;/);
  assert.match(js, /if \(handleSlackMeListContinuationEnter\(\)\) \{/);
  assert.match(js, /sendBackgroundRequest\("ZIP_GET_PASS_TRANSITION_RECIPIENTS", \{\}\)/);
  assert.match(js, /sendBackgroundRequest\("ZIP_REHYDRATE_PASS_TRANSITION_MEMBERS", \{\s*force: true,\s*allowCreateTab: true\s*\}\)/);
  assert.match(js, /sendBackgroundRequest\("ZIP_SLACK_API_SEND_TO_SELF"/);
  assert.match(js, /sendBackgroundRequest\("ZIP_SLACK_API_SEND_TO_USER"/);
  assert.match(js, /preferBotDmDelivery:\s*true/);
  assert.match(js, /requireBotDelivery:\s*true/);
  assert.match(js, /allowBotDelivery:\s*true/);
  assert.match(js, /PASS-TRANSITION self-share sent to your Slack DM/);
  assert.match(js, /Sending visible ticket list to ZipTool panel/);
  assert.match(js, /SLACK_IT_TO_ME delivered to ZipTool panel/);
  assert.doesNotMatch(js, /buildSlackMeNoteMarkdown\(noteText\)/);
  assert.doesNotMatch(js, /openSlackMeDialog\(\{ mode: "self" \}\)/);
  assert.doesNotMatch(js, /@SLACK ME sent to your Slack DM\./);
});

test("sidepanel tracks staged Slacktivation progress in the footer and toast", () => {
  const js = fs.readFileSync(SIDEPANEL_JS_PATH, "utf8");
  const css = fs.readFileSync(SIDEPANEL_CSS_PATH, "utf8");

  assert.match(js, /const SLACKTIVATION_IMPORT_PROGRESS_MESSAGE = "SLACKTIVATING ZIP\.KEY…";/);
  assert.match(js, /const SLACKTIVATION_REFRESH_PROGRESS_MESSAGE = "Refreshing stored Slacktivation credentials…";/);
  assert.match(js, /const SLACKTIVATION_PASS_TRANSITION_PROGRESS_MESSAGE = "Hydrating PASS-TRANSITION roster…";/);
  assert.match(js, /const SLACKTIVATION_PHASE1_SUCCESS_MESSAGE = "SLACKTIVATED! Please click the Z avatar to log into Slack\.";/);
  assert.match(js, /const SLACKTIVATION_PHASE2_PROBE_MESSAGE = "Checking adobedx\.slack\.com session…";/);
  assert.match(js, /const SLACKTIVATION_PHASE2_WAIT_MESSAGE = "Waiting for Slack sign-in in adobedx\.slack\.com…";/);
  assert.match(js, /const SLACKTIVATION_PHASE2_FINALIZING_MESSAGE = "Finalizing Slack API validation…";/);
  assert.match(js, /const SLACKTIVATION_PHASE2_SUCCESS_MESSAGE = "SLACKTIVATED! Slack login confirmed\. Slack actions are ready\.";/);
  assert.match(js, /slacktivationStatusPhase:\s*""/);
  assert.match(js, /slacktivationStatusStep:\s*""/);
  assert.match(js, /slacktivationStatusTone:\s*""/);
  assert.match(js, /slacktivationStatusMessage:\s*""/);
  assert.match(js, /function normalizeSlacktivationFooterTone\(value\)/);
  assert.match(js, /function syncSlacktivationFooterStatusState\(\)/);
  assert.match(js, /function setSlacktivationFooterStatus\(tone,\s*message,\s*options\)/);
  assert.match(js, /function clearSlacktivationFooterStatus\(options\)/);
  assert.match(js, /function setSlacktivationPhase2Progress\(message,\s*step\)/);
  assert.match(js, /function setSlacktivationPhase2Success\(message\)/);
  assert.match(js, /showToast\(String\(opts\.toastMessage \|\| text\)\.trim\(\), Number\(opts\.durationMs\) \|\| 2400, \{ tone: "success" \}\);/);
  assert.match(js, /async function ensurePassAiSlacktivationHydrated\(options\)/);
  assert.match(js, /async function ensurePassAiSlackRosterHydrated\(options\)/);
  assert.match(js, /setSlacktivationFooterStatus\("loading", startMessage,/);
  assert.match(js, /setSlacktivationFooterStatus\("success", successMessage,/);
  assert.match(js, /setSlacktivationPhase2Progress\(SLACKTIVATION_PHASE2_PROBE_MESSAGE,\s*"probe_session"\)/);
  assert.match(js, /setSlacktivationPhase2Progress\(SLACKTIVATION_PHASE2_WAIT_MESSAGE,\s*"waiting_for_sign_in"\)/);
  assert.match(js, /setSlacktivationPhase2Progress\(SLACKTIVATION_PHASE2_FINALIZING_MESSAGE,\s*"finalizing_api_validation"\)/);
  assert.match(js, /setSlacktivationPhase2Success\(\);/);

  assert.match(css, /\.zip-footer-status\.success \{/);
  assert.match(css, /\.zip-footer-status\.success::before \{/);
  assert.match(css, /\.zip-toast\[data-tone="success"\] \{/);
});

test("sidepanel preserves verified Slacktivated state across reload and transient no-tab refreshes", () => {
  const js = fs.readFileSync(SIDEPANEL_JS_PATH, "utf8");

  assert.match(js, /if \(cachedMode !== "openid" && cachedMode !== "web" && cachedMode !== "api"\)/);
  assert.match(js, /recordSlackProbeEvent\("slack_probe_cached_state_loaded",\s*\{/);
  assert.match(js, /const persistableMode = requestedMode === "openid" \|\| requestedMode === "web" \|\| requestedMode === "api";/);
  assert.match(js, /if \(\s*wasReady[\s\S]*&& isTransientSlackAuthProbeFailureMessage\(message\)\s*\) \{[\s\S]*recordSlackProbeEvent\("slack_probe_verified_state_preserved",\s*\{[\s\S]*source:\s*"transient_web_auth_failure"/);
});

test("sidepanel ships ZIP DEBUG INFO footer icon and hidden console snapshot", () => {
  const html = fs.readFileSync(SIDEPANEL_HTML_PATH, "utf8");
  const js = fs.readFileSync(SIDEPANEL_JS_PATH, "utf8");
  const css = fs.readFileSync(SIDEPANEL_CSS_PATH, "utf8");

  assert.match(html, /id="zipDebugConsole"/);
  assert.match(html, /id="zipDebugConsoleBody"/);
  assert.match(html, /id="zipDebugConsoleTitle"/);
  assert.match(html, /id="zipDebugConsoleMeta"/);
  assert.match(html, /id="zipDebugToggleStatus"/);
  assert.match(html, /id="zipDebugLogOutput"/);
  assert.match(html, /id="zipStatus"[\s\S]*id="zipDebugToggleBtn"[\s\S]*id="zipAppVersionLink"/);
  assert.match(html, /id="zipDebugToggleBtn"[\s\S]*Shift\+click to expand\./);

  assert.match(js, /const ZIP_DEBUG_TOGGLE_LABEL = "DEBUG INFO";/);
  assert.match(js, /const ZIP_DEBUG_TOGGLE_META = "Click copies\. Shift\+click toggles details\.";/);
  assert.match(js, /const ZIP_DEBUG_COPY_STATUS = "Copied to clipboard";/);
  assert.match(js, /const ZIP_DEBUG_COPY_TOAST_MESSAGE = "ZIP DEBUG INFO copied\.";/);
  assert.match(js, /debugConsoleCollapsed:\s*true/);
  assert.match(js, /debugCopyStatus:\s*""/);
  assert.match(js, /debugEvents:\s*\[\]/);
  assert.match(js, /debugStatusHistory:\s*\[\]/);
  assert.match(js, /debugConsole:\s*\$\("zipDebugConsole"\)/);
  assert.match(js, /debugConsoleBody:\s*\$\("zipDebugConsoleBody"\)/);
  assert.match(js, /debugConsoleTitle:\s*\$\("zipDebugConsoleTitle"\)/);
  assert.match(js, /debugConsoleMeta:\s*\$\("zipDebugConsoleMeta"\)/);
  assert.match(js, /debugToggleBtn:\s*\$\("zipDebugToggleBtn"\)/);
  assert.match(js, /debugToggleStatus:\s*\$\("zipDebugToggleStatus"\)/);
  assert.match(js, /debugLogOutput:\s*\$\("zipDebugLogOutput"\)/);
  assert.match(js, /function recordZipDebugEvent\(channel,\s*message,\s*details,\s*level,\s*atOverride\)/);
  assert.match(js, /function composeZipDebugConsoleOutput\(\)/);
  assert.match(js, /function composeZipDebugConsoleFallback\(error\)/);
  assert.match(js, /function getZipDebugConsoleSnapshot\(\)/);
  assert.match(js, /function renderDebugConsole\(\)/);
  assert.match(js, /function setDebugConsoleCollapsed\(collapsed\)/);
  assert.match(js, /async function copyDebugConsoleToClipboard\(\)/);
  assert.match(js, /"preferBotDmDelivery"/);
  assert.match(js, /"requireBotDelivery"/);
  assert.match(js, /"allowBotDelivery"/);
  assert.match(js, /summary\.directChannelIdPresent = true;/);
  assert.match(js, /pushZipDebugSection\(lines,\s*"slacktivation",\s*\[/);
  assert.match(js, /pushZipDebugSection\(\s*lines,\s*"recent_slack_probe",/);
  assert.match(js, /showToast\(ZIP_DEBUG_COPY_TOAST_MESSAGE,\s*1800,\s*\{\s*tone:\s*"success"\s*\}\);/);
  assert.match(js, /document\.body\.classList\.toggle\("zip-debug-open",\s*open\);/);
  assert.match(js, /els\.debugToggleBtn\.addEventListener\("click",\s*\(event\)\s*=>\s*\{[\s\S]*if \(event\.shiftKey\) \{[\s\S]*setDebugConsoleCollapsed\(!state\.debugConsoleCollapsed\);[\s\S]*void copyDebugConsoleToClipboard\(\);/);

  assert.match(css, /\.zip-footer-debug-btn\s*\{/);
  assert.match(css, /\.zip-footer-debug-btn\[data-state="expanded"\]\s*\{/);
  assert.match(css, /body\.zip-debug-open \.body\s*\{/);
  assert.match(css, /\.zip-debug-console\s*\{[\s\S]*position:\s*fixed;[\s\S]*bottom:\s*calc\(var\(--zip-footer-height\)\s*-\s*1px\);/);
  assert.match(css, /\.zip-debug-console\.is-open\s*\{/);
  assert.match(css, /\.zip-debug-console-status\s*\{/);
  assert.match(css, /\.zip-debug-console-output\s*\{[\s\S]*inline-size:\s*100%;/);
});

test("sidepanel styles avoid custom Slack header spinner overlay", () => {
  const css = fs.readFileSync(SIDEPANEL_CSS_PATH, "utf8");
  assert.doesNotMatch(css, /#zipSlacktivatedBtn\.is-network-loading::after/);
  assert.match(css, /\.zip-slack-me-dialog\s*\{[\s\S]*width:\s*min\(980px,\s*calc\(100vw\s*-\s*12px\)\);/);
  assert.match(css, /\.zip-slack-me-recipient-field\s*\{/);
  assert.match(css, /\.zip-slack-me-recipient-chip\s*\{/);
  assert.match(css, /\.zip-slack-me-recipient-select-wrap\s*\{/);
  assert.match(css, /\.zip-slack-me-recipient-select\s*\{/);
  assert.match(css, /\.zip-slack-me-recipient-help\s*\{/);
  assert.match(css, /\.zip-slack-me-editor-shell\s*\{[\s\S]*border:\s*2px\s+solid/);
  assert.match(css, /\.zip-slack-me-toolbar\s*\{[\s\S]*flex-wrap:\s*nowrap;/);
  assert.match(css, /\.zip-slack-me-toolbar\s*\{[\s\S]*overflow-x:\s*auto;/);
  assert.match(css, /\.zip-slack-me-input\s*\{[\s\S]*min-height:\s*180px;/);
  assert.match(css, /\.zip-slack-me-input\s*\{[\s\S]*var\(--spectrum-font-size-300\)/);
  assert.match(css, /#zipSlackMeSendBtn\s*\{[\s\S]*min-width:\s*92px;/);
});

test("content script supports Slack auth identity details and @ME markdown DM action", () => {
  const source = fs.readFileSync(CONTENT_PATH, "utf8");
  assert.match(source, /async function slackAuthTestAction\(inner\)/);
  assert.match(source, /function isSlackStatusAssetUrl\(value\)/);
  assert.match(source, /function sanitizeSlackAvatarCandidate\(value,\s*statusIconUrl\)/);
  assert.match(source, /function pickSlackSessionStatusIconUrl\(candidate\)/);
  assert.match(source, /user_name:/);
  assert.match(source, /avatar_url:/);
  assert.match(source, /status_icon:/);
  assert.match(source, /status_message:/);
  assert.match(source, /const hasSessionSignals = !!\(/);
  assert.match(source, /session_only:\s*true/);
  assert.match(source, /if \(looksSignedIn && hasSessionSignals\) \{/);
  assert.match(source, /Slack session detected; waiting for web token capture\./);
  assert.match(source, /xox\[a-z\]-/);
  assert.match(source, /return "";/);
  assert.match(source, /code === "missing_scope"/);
  assert.match(source, /code === "insufficient_scope"/);
  assert.match(source, /code === "not_allowed_token_type"/);
  assert.match(source, /code === "channel_not_found"/);
  assert.match(source, /code === "not_in_channel"/);
  assert.match(source, /code === "workspace_mismatch"/);
  assert.match(source, /function isSlackWebSessionToken\(value\)/);
  assert.match(source, /const profileAvatarUrl = sanitizeSlackAvatarCandidate\(profile\.avatarUrl \|\| "", statusIconUrl \|\| profile\.statusIconUrl \|\| ""\);/);
  assert.match(source, /if \(profileAvatarUrl\) avatarUrl = profileAvatarUrl;/);
  assert.match(source, /avatarUrl = sanitizeSlackAvatarCandidate\(avatarUrl,\s*statusIconUrl\);/);
  assert.match(source, /async function resolveSlackUserIdFromChannelHistory\(workspaceOrigin,\s*channelId,\s*mention\)/);
  assert.match(source, /const postToChannel = \(targetChannelId,\s*reasonTag\) => postSlackApi\(workspaceOrigin,\s*"\/api\/chat\.postMessage"/);
  assert.match(source, /shouldRecoverWithDmOpen/);
  assert.match(source, /parse:\s*singularityTag \? "none" : "full"/);
  assert.match(source, /postSlackApi\(workspaceOrigin,\s*"\/api\/conversations\.open"/);
  assert.match(source, /postSlackApi\(workspaceOrigin,\s*"\/api\/conversations\.replies",\s*repliesFields\)/);
  assert.doesNotMatch(source, /preferredToken:\s*preferredUserToken \|\| ""/);

  assert.match(source, /async function slackSendMarkdownToSelfAction\(inner\)/);
  assert.match(source, /async function slackMarkUnreadAction\(inner\)/);
  assert.match(source, /inner\.action === "slackMarkUnread"/);
  assert.match(source, /\/api\/chat\.postMessage/);
  assert.match(source, /\/api\/conversations\.open/);
  assert.match(source, /\/api\/conversations\.mark/);
  assert.match(source, /\/api\/subscriptions\.thread\.mark/);
  assert.doesNotMatch(source, /\/api\/files\.upload/);
  assert.doesNotMatch(source, /\/api\/files\.info/);
  assert.match(source, /inner\.action === "slackSendMarkdownToSelf"/);
  assert.match(source, /mrkdwn:\s*true,/);
  assert.match(source, /parse:\s*"none"/);
});

test("Slack token bridge captures tokens from body and headers", () => {
  const source = fs.readFileSync(SLACK_TOKEN_BRIDGE_PATH, "utf8");
  assert.match(source, /\(\?:xoxe\\\.\)\?xox\[a-z\]-/);
  assert.match(source, /function inspectHeaders\(headers, depth\)/);
  assert.match(source, /if \(init && Object\.prototype\.hasOwnProperty\.call\(init, "headers"\)\) inspectHeaders\(init\.headers, 0\);/);
  assert.match(source, /if \(input && typeof input === "object" && Object\.prototype\.hasOwnProperty\.call\(input, "headers"\)\) inspectHeaders\(input\.headers, 0\);/);
  assert.match(source, /window\.XMLHttpRequest\.prototype\.setRequestHeader/);
  assert.match(source, /inspect\(value, 0\);/);
});

test("options page keeps ZIP.KEY hydration avatar-menu only", () => {
  const source = fs.readFileSync(OPTIONS_PATH, "utf8");
  const html = fs.readFileSync(OPTIONS_HTML_PATH, "utf8");
  assert.match(source, /ZIP\.KEY is not loaded\. Open ZipTool and use the avatar menu to SLACKTIVATE when needed\./);
  assert.match(source, /Stored ZIP\.KEY is incomplete or stale/);
  assert.doesNotMatch(source, /ZIP_IMPORT_KEY_PAYLOAD/);
  assert.doesNotMatch(source, /function normalizeSlackToken\(value\)/);
  assert.doesNotMatch(source, /function parseZipKeyPayload\(rawText\)/);
  assert.doesNotMatch(html, /Import ZIP\.KEY/);
  assert.doesNotMatch(html, /id="zipKeyFile"/);
  assert.doesNotMatch(html, /id="zipKeyText"/);
  assert.match(html, /Avatar menu only/);
});

test("background removes legacy Slack OAuth and popup-login handlers", () => {
  const source = fs.readFileSync(BACKGROUND_PATH, "utf8");
  assert.doesNotMatch(source, /ZIP_SLACK_OAUTH_STATUS/);
  assert.doesNotMatch(source, /ZIP_SLACK_OAUTH_SIGN_IN/);
  assert.doesNotMatch(source, /ZIP_SLACK_OAUTH_SIGN_OUT/);
  assert.doesNotMatch(source, /ZIP_PASS_AI_SLACK_SEND/);
  assert.doesNotMatch(source, /ZIP_PASS_AI_SLACK_POLL/);
  assert.doesNotMatch(source, /ZIP_OPEN_SLACK_LOGIN/);
  assert.doesNotMatch(source, /ZIP_CLOSE_WINDOW/);
  assert.match(source, /SLACK_OPENID_AUTHORIZE_URL/);
  assert.match(source, /SLACK_OPENID_TOKEN_URL/);
  assert.match(source, /SLACK_OPENID_USERINFO_URL/);
  assert.match(source, /MENU_CLEAR_KEY/);
  assert.match(source, /MENU_CLEAR_KEY_SEPARATOR/);
  assert.match(source, /MENU_CLEAR_KEY_LABEL/);
  assert.match(source, /const ASK_TEAM_EMAIL = "PrimetimeTAMs@adobe\.com";/);
  assert.match(source, /const MENU_ASK_TEAM_LABEL = "✉ Ask the Team";/);
  assert.doesNotMatch(source, /ZIP_TOOL_BETA_SIGNATURE_SLUG/);
  assert.doesNotMatch(source, /ASK_ERIC_EMAIL/);
  assert.match(source, /msg\.type === "ZIP_CHECK_SECRETS"/);
  assert.match(source, /msg\.type === "ZIP_CLEAR_KEY"/);
  assert.match(source, /msg\.type === "ZIP_IMPORT_KEY_PAYLOAD"/);
  assert.match(source, /type:\s*"ZIP_KEY_CLEARED"/);
  assert.match(source, /action === "clearZipKey"/);
  assert.match(source, /id:\s*MENU_CLEAR_KEY_SEPARATOR,[\s\S]*type:\s*"separator"[\s\S]*id:\s*MENU_CLEAR_KEY/);
  assert.match(source, /const SLACK_OPENID_DEFAULT_REDIRECT_PATH = "slack-user";/);
  assert.match(source, /const ZIP_SLACK_REDIRECT_URI_STORAGE_KEY = "zip_slack_redirect_uri";/);
  assert.match(source, /function resolveSlackOpenIdRedirectUriCandidates\(config\)/);
  assert.match(source, /function isSlackOpenIdRedirectMismatchError\(message\)/);
  assert.match(source, /msg\.type === "ZIP_SLACK_OPENID_AUTH"/);
  assert.match(source, /msg\.type === "ZIP_SLACK_OPENID_STATUS"/);
  assert.match(source, /msg\.type === "ZIP_SLACK_API_AUTH_TEST"/);
  assert.match(source, /msg\.type === "ZIP_SLACK_API_SEND_TO_SELF"/);
  assert.match(source, /function isSlackWebSessionToken\(value\)/);
  assert.match(source, /const useWebSessionTransport = isSlackWebSessionToken\(authToken\);/);
  assert.match(source, /msg\.type === "ZIP_SLACK_API_QAI_SEND"/);
  assert.match(source, /msg\.type === "ZIP_SLACK_API_QAI_POLL"/);
  assert.match(source, /async function slackSendToSingularityViaApi\(input\)/);
  assert.match(source, /async function resolveSlackUserIdFromChannelHistoryViaApi\(apiOrigin,\s*token,\s*channelId,\s*mention\)/);
  assert.match(source, /link_names:\s*"1"/);
  assert.match(source, /parse:\s*effectiveSingularityUserId \? "none" : "full"/);
  assert.match(source, /async function slackPollSingularityThreadViaApi\(input\)/);
  assert.match(source, /async function slackMarkUnreadViaWorkspaceSession\(input, reasonCode\)/);
  assert.match(source, /async function postSlackApiViaWorkspaceSession\(input\)/);
  assert.match(source, /action:\s*"slackMarkUnread"/);
  assert.match(source, /action:\s*"slackApiProxy"/);
  assert.match(source, /async function markSlackMessageUnreadViaApiToken\(workspaceOrigin,\s*token,\s*channelId,\s*messageTs,\s*readCursorTs\)/);
  assert.match(source, /async function slackSendMarkdownToSelfViaApi\(input\)/);
  assert.match(source, /const allowWorkspaceTabBootstrap = body\.autoBootstrapSlackTab !== false;/);
  assert.match(source, /function resolveExpectedSlackAuthorUserId\(input,\s*openIdSession\)/);
  assert.match(source, /async function slackSendMarkdownToSelfViaWorkspaceSession\(input, reasonCode\)/);
  assert.match(source, /function isAllowedSlackWorkspaceHost\(host, workspaceHost\)/);
  assert.match(source, /if \(!isAllowedSlackWorkspaceHost\(tabHost, expectedHost\)\) continue;/);
  assert.match(source, /slackSendMarkdownToSelfViaWorkspaceSession\(body,\s*"workspace_session_primary"\)/);
  assert.match(source, /primarySessionDelivery[\s\S]*primarySessionDelivery\.ok/);
  assert.match(source, /if \(allowBotDelivery\) \{[\s\S]*const botFallback = primaryBotFailure \|\| await slackSendMarkdownToSelfViaBotApi\(body,\s*tokens\);/);
  assert.match(source, /const requireNativeNewMessage = body\.requireNativeNewMessage !== false;/);
  assert.match(source, /const preferBotDmDelivery = body\.preferBotDmDelivery !== false;/);
  assert.match(source, /const requireBotDelivery = body\.requireBotDelivery === true;/);
  assert.match(source, /const allowBotDelivery = body\.allowBotDelivery === true \|\| requireBotDelivery;/);
  assert.match(source, /function normalizeSlackStatusMessage\(value\)/);
  assert.match(source, /status_message:/);
  assert.match(source, /status_icon:/);
  assert.match(source, /async function slackSendMarkdownToSelfViaBotApi\(input,\s*resolvedTokens\)/);
  assert.match(source, /const botDeliveryToken = normalizeSlackApiToken\(tokens\.botToken\);/);
  assert.match(source, /const botCandidates = Array\.isArray\(tokens && tokens\.botCandidates\)/);
  assert.match(source, /const userDeliveryToken = normalizeSlackApiToken\(tokens\.userToken\);/);
  assert.match(source, /const userCandidates = Array\.isArray\(tokens && tokens\.userCandidates\)/);
  assert.match(source, /const botResolved = uniq\(botCandidates\.concat\(userCandidates\)\)\.filter\(\(token\) => isSlackBotApiToken\(token\)\);/);
  assert.match(source, /const userResolved = uniq\(userCandidates\.concat\(botCandidates\)\)\.filter\(\(token\) => isSlackUserOAuthToken\(token\)\);/);
  assert.match(source, /const hasUserOAuthCandidate = tokenAttempts\.length > 0;/);
  assert.match(source, /const expectedUserId = resolveExpectedSlackAuthorUserId\(body,\s*openIdSession\);/);
  assert.match(source, /const expectedAuthorUserId = resolveExpectedSlackAuthorUserId\(body,\s*openIdSession\);/);
  assert.match(source, /if \(!hasUserOAuthCandidate\) \{/);
  assert.match(source, /const tokenAttempts = \[];/);
  assert.match(source, /for \(let i = 0; i < userCandidates\.length; i \+= 1\) \{/);
  assert.match(source, /for \(let i = 0; i < tokenAttempts\.length; i \+= 1\)/);
  assert.match(source, /function isSlackUserOAuthToken\(value\)/);
  assert.doesNotMatch(source, /return \/\^xoxp-\//);
  assert.match(source, /\^\(\?:xoxe\\\.\)\?xox\[a-z\]-/);
  assert.match(source, /lastFailureCode = "slack_identity_mismatch";/);
  assert.match(source, /Slack API token does not match the active Slack user\./);
  assert.match(source, /function isSlackBotApiToken\(value\)/);
  assert.match(source, /function isSlackTokenInvalidationCode\(code\)/);
  assert.match(source, /async function invalidateStoredSlackToken\(token\)/);
  assert.match(source, /async function hydratePassTransitionRecipientsViaWorkspaceSession\(options\)/);
  assert.match(source, /const SLACK_TOKEN_FAILURE_BACKOFF_MS = 2 \* 60 \* 1000;/);
  assert.match(source, /const slackTokenBackoffUntilByToken = new Map\(\);/);
  assert.match(source, /function markSlackTokenBackoff\(token\)/);
  assert.match(source, /function clearSlackTokenBackoff\(token\)/);
  assert.match(source, /if \(isSlackTokenTemporarilyBackedOff\(attemptToken\)\) \{/);
  assert.match(source, /if \(isSlackTokenInvalidationCode\(lastFailureCode\)\) \{/);
  assert.match(source, /SLACK_IT_TO_ME requires a Slack bot token for guaranteed new-message delivery\./);
  assert.match(source, /SLACK_IT_TO_ME requires a Slack user\/session token for DM delivery\./);
  assert.match(source, /\/api\/chat\.postMessage/);
  assert.match(source, /\/api\/conversations\.open/);
  assert.match(source, /direct_channel_id:/);
  assert.doesNotMatch(source, /if \(isBotToken\) \{/);
  assert.match(source, /delivery_mode:\s*"bot_direct_channel"/);
  assert.match(source, /delivery_mode:\s*"user_direct_channel"/);
  assert.match(source, /delivery_mode:\s*"workspace_session_dm"/);
  assert.match(source, /autoBootstrapSlackTab:\s*allowWorkspaceTabBootstrap/);
  assert.doesNotMatch(source, /requires a Slack user token/);
  assert.doesNotMatch(source, /files\.getUploadURLExternal/);
  assert.doesNotMatch(source, /Download: <"\s*\+\s*csvPermalink\s*\+\s*"\|CSV>/);
  assert.match(source, /launchWebAuthFlow/);
  assert.doesNotMatch(source, /type:\s*["']popup["']/);
});
